/// <reference types="cypress" />

describe('Pokemon Page Navigation Spec', () => {
	before(() => {
		cy.visit('/')
		cy.intercept('GET', 'https://api.hatchways.io/assessment/pokemon', {
			statusCode: 200,
			fixture: 'pokemon.json'
		})
	})
	it('should render pokemon portal', () => {
		cy.get('[data-cy=pokemon-portal]').should('exist')
		cy.get('[data-cy=filter-nav]').should('exist')
		cy.get('[data-cy=search-bar-name]').should('exist')
		cy.get('[data-cy=search-bar-tags]').should('exist')
		cy.get('[data-cy=list-pokemon]').should('exist')
	})
	it('should have a list of pokemon', () => {
		cy.get('[data-cy=list-pokemon]')
		cy.should('exist')
		cy.should('contain', 'Andrew Vallejo')
		cy.get('[data-cy=pokemon-portal]').scrollTo('bottom')
		cy.get('[data-cy=list-pokemon]')
		cy.should('contain', 'Maire')
		cy.get('[data-cy=pokemon-portal]').scrollTo('top')
	})
	it('a pokemon should have a profile', () => {
		cy.get('[cy-data="pokemon-1"]')
		cy.should('contain', 'Andrew Vallejo')
		cy.should('contain', 'Email:')
		cy.should('contain', 'andrew.a.vallejo@gmail.com')
		cy.should('contain', 'Company:')
		cy.should('contain', 'Hatchways')
		cy.should('contain', 'Skill:')
		cy.should('contain', 'JavaScript')
		cy.should('contain', 'Average:')
		cy.should('contain', '88.875%')
		cy.get('[cy-data="pokemon-1"] > .flex-row > .flex-1 > .absolute').click()
		cy.get('[cy-data="pokemon-1"]')
		cy.should('contain', 'Test 1:')
		cy.should('contain', '78%')
		cy.should('contain', 'Test 8:')
		cy.should('contain', '87%')
		cy.get('[cy-data="pokemon-1"] > .w-full > :nth-child(2) > .px-5.flex-col > .py-2 > [data-cy="testscores-list"]')
		cy.get('[cy-data="pokemon-1"] > .flex-row > .flex-1 > .absolute').click()
	})
	it('should be able to add tags to any pokemon', () => {
		cy.addTags()
		cy.get('[cy-data="pokemon-1"]')
		cy.should('contain', 'tag1')
		cy.should('contain', 'tag2')
		cy.should('contain', 'tag3')
		cy.get('[cy-data="pokemon-2"]')
		cy.should('contain', 'tag1')
		cy.should('contain', 'tag2')
		cy.get('[cy-data="pokemon-3"]')
		cy.should('contain', 'tag2')
		cy.should('contain', 'tag3')
	})

	it('should be able to filter pokemon by name', () => {
		cy.get('[data-cy=search-bar-name]').should('have.attr', 'placeholder', 'Search by name')
		cy.get('[data-cy=search-bar-name]').type('An')
		cy.get('[data-cy=list-pokemon]')
		cy.should('contain', 'Andrew Vallejo')
		cy.should('contain', 'Laurens')
		cy.should('contain', 'Rory')
		cy.should('contain', 'Rosalynd')
		cy.get('[data-cy=search-bar-name]').clear().type('Andrew')
		cy.get('[data-cy=list-pokemon]')
		cy.should('contain', 'Andrew Vallejo')
		cy.should('not.contain', 'Laurens')
		cy.should('not.contain', 'Rory')
		cy.should('not.contain', 'Rosalynd')
		cy.get('[data-cy=search-bar-name]').clear()
	})

	it('should be able to filter pokemon by tag', () => {
		cy.get('[data-cy=search-bar-tags]').should('have.attr', 'placeholder', 'Search by tags')
		cy.get('[data-cy=search-bar-tags]').type('tag2')
		cy.get('[data-cy=list-pokemon]')
		cy.should('contain', 'Andrew Vallejo')
		cy.should('contain', 'Clarke')
		cy.should('contain', 'Laurens')
		cy.get('[data-cy=search-bar-tags]').clear().type('tag1')
		cy.get('[data-cy=list-pokemon]')
		cy.should('contain', 'Andrew Vallejo')
		cy.should('contain', 'Clarke')
		cy.should('not.contain', 'Laurens')
		cy.get('[data-cy=search-bar-tags]').clear().type('tag3')
		cy.get('[data-cy=list-pokemon]')
		cy.should('contain', 'Andrew Vallejo')
		cy.should('contain', 'Laurens')
		cy.should('not.contain', 'Clarke')
		cy.get('[data-cy=search-bar-tags]').clear()
	})

	it('should be able to filter pokemon by name and tag', () => {
		cy.get('[data-cy=search-bar-name]').type('An')
		cy.get('[data-cy=search-bar-tags]').type('tag2')
		cy.get('[data-cy=list-pokemon]')
		cy.should('contain', 'Andrew Vallejo')
		cy.should('contain', 'Andrew')
		cy.should('not.contain', 'Clarke')
		cy.get('[data-cy=search-bar-name]').clear().type('An')
		cy.get('[data-cy=search-bar-tags]').clear().type('tag1')
		cy.get('[data-cy=list-pokemon]')
		cy.should('contain', 'Andrew Vallejo')
		cy.should('not.contain', 'Clarke')
		cy.should('not.contain', 'Laurens')
		cy.get('[data-cy=search-bar-name]').clear().type('A')
		cy.get('[data-cy=search-bar-tags]').clear().type('tag3')
		cy.get('[data-cy=list-pokemon]')
		cy.should('contain', 'Andrew Vallejo')
		cy.should('contain', 'Laurens')
		cy.should('not.contain', 'Clarke')
		cy.get('[data-cy=search-bar-name]').clear().type('Andrew')
		cy.get('[data-cy=search-bar-tags]').clear().type('tag3')
		cy.get('[data-cy=list-pokemon]')
		cy.should('contain', 'Andrew Vallejo')
		cy.should('not.contain', 'Laurens')
		cy.should('not.contain', 'Clarke')
		cy.get('[data-cy=search-bar-name]').clear()
		cy.get('[data-cy=list-pokemon]')
		cy.should('contain', 'Andrew Vallejo')
		cy.should('contain', 'Laurens')
		cy.should('not.contain', 'Clarke')
		cy.get('[data-cy=search-bar-tags]').clear()
	})
})
